### ISSUE TITLE
utilities.scd

### ISSUE THREAD

**Issue by bgrange** [brunoruviaro/SynthDefs-for-Patterns#3]
Where is this utilities.scd file?

**Comment by brunoruviaro** [comment]
What utilities.scd file?
Sorry this repo is really not very well developed yet... I just threw in some SynthDefs and plan to continue working on it, but haven't had time.

**Comment by brunoruviaro** [comment]
Sorry, I remember now. I think the utilities.scd was part of a proposal by another user to simplify the sorting and access to SynthDefs and Pattern examples. It was just an idea that we began to explore but left unfinished. For now, you should probably ignore that line and just the SynthDef as is.

**Comment by bgrange** [comment]
noted. Thank you.
